version: "3.3"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8001:80'
    volumes:
      - ./api/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./api:/var/www/html:delegated
    env_file:
      - ./env/.env
  mysql:
    image: mysql:8.0.25
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ./vols/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - "8002:80"
